app:
  name: 'kitchen-service'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5004

postgres:
  pool_max: 2
  dsn_url: host=127.0.0.1 user=postgres password=P@ssw0rd dbname=postgres sslmode=disable

rabbitmq:
  url: amqp://guest:guest@127.0.0.1:5672/

logger:
  log_level: 'debug'
  rollbar_env: 'kitchen-service'